// Strudel Autocomplete Data
// Comprehensive suggestions for functions, methods, samples, and more

const StrudelAutocomplete = {
    // Core pattern functions
    patternFunctions: [
        { label: 's', detail: 'sound/sample', info: 'Play a sound or sample. Example: s("bd")' },
        { label: 'n', detail: 'note number', info: 'Play MIDI note number. Example: n("0 2 4 7")' },
        { label: 'note', detail: 'note name', info: 'Play note by name. Example: note("c4 e4 g4")' },
        { label: 'sound', detail: 'sound pattern', info: 'Alternative to s(). Play sounds.' },
        { label: 'chord', detail: 'chord pattern', info: 'Play chords. Example: chord("<Cm7 Fm7>")' },
        { label: 'scale', detail: 'scale pattern', info: 'Set scale. Example: scale("c4:minor")' },
        { label: 'mode', detail: 'mode pattern', info: 'Set mode for notes' },
        { label: 'run', detail: 'number sequence', info: 'Pattern of numbers from 0 to n-1. Example: n(run(4))' },
        { label: 'beat', detail: 'rhythm structure', info: 'Creates structure pattern from cycle divisions. Example: s("bd").beat("0,7,10", 16)' }
    ],

    // Sample shortcuts (drum sounds)
    sampleShortcuts: [
        { label: 'bd', detail: 'bass drum', info: 'Bass drum sample' },
        { label: 'sd', detail: 'snare drum', info: 'Snare drum sample' },
        { label: 'cp', detail: 'clap', info: 'Clap sample' },
        { label: 'hh', detail: 'hi-hat closed', info: 'Closed hi-hat sample' },
        { label: 'oh', detail: 'hi-hat open', info: 'Open hi-hat sample' },
        { label: 'cr', detail: 'crash', info: 'Crash cymbal sample' },
        { label: 'ride', detail: 'ride cymbal', info: 'Ride cymbal sample' },
        { label: 'lt', detail: 'low tom', info: 'Low tom sample' },
        { label: 'mt', detail: 'mid tom', info: 'Mid tom sample' },
        { label: 'ht', detail: 'high tom', info: 'High tom sample' },
        { label: 'rim', detail: 'rimshot', info: 'Rimshot sample' },
        { label: 'rd', detail: 'ride', info: 'Ride cymbal' }
    ],

    // Effects
    effects: [
        { label: 'gain', detail: 'volume (0-1)', info: 'Set volume level. Example: .gain(0.8)' },
        { label: 'room', detail: 'reverb (0-1)', info: 'Add reverb/room effect. Example: .room(0.5)' },
        { label: 'delay', detail: 'delay (0-1)', info: 'Add delay effect. Example: .delay(0.25)' },
        { label: 'pan', detail: 'stereo (-1 to 1)', info: 'Pan left/right. Example: .pan(0.5)' },
        { label: 'lpf', detail: 'low-pass filter', info: 'Low-pass filter frequency. Example: .lpf(1000)' },
        { label: 'hpf', detail: 'high-pass filter', info: 'High-pass filter frequency. Example: .hpf(200)' },
        { label: 'lpq', detail: 'lpf resonance', info: 'Low-pass filter resonance' },
        { label: 'hpq', detail: 'hpf resonance', info: 'High-pass filter resonance' },
        { label: 'shape', detail: 'distortion (0-1)', info: 'Add distortion. Example: .shape(0.5)' },
        { label: 'crush', detail: 'bitcrush (1-16)', info: 'Bitcrusher effect. Example: .crush(4)' },
        { label: 'phaser', detail: 'phaser', info: 'Add phaser effect. Example: .phaser(4)' },
        { label: 'vowel', detail: 'vowel filter', info: 'Vowel formant filter' },
        { label: 'fm', detail: 'FM synthesis', info: 'Frequency modulation' },
        { label: 'am', detail: 'AM synthesis', info: 'Amplitude modulation' },
        { label: 'vib', detail: 'vibrato', info: 'Add vibrato. Example: .vib(5)' },
        { label: 'vibmod', detail: 'vibrato depth', info: 'Vibrato modulation depth' },
        { label: 'tremolo', detail: 'tremolo', info: 'Add tremolo effect' },
        { label: 'speed', detail: 'playback speed', info: 'Change sample speed. Example: .speed(0.5)' },
        { label: 'attack', detail: 'attack time', info: 'Envelope attack. Example: .attack(0.01)' },
        { label: 'release', detail: 'release time', info: 'Envelope release. Example: .release(0.2)' },
        { label: 'decay', detail: 'decay time', info: 'Envelope decay' },
        { label: 'sustain', detail: 'sustain level', info: 'Envelope sustain' },
        { label: 'bank', detail: 'sample bank', info: 'Select sample bank. Example: .bank("tr909")' },
        { label: 'cut', detail: 'cut group', info: 'Cut group for sample stopping' },
        { label: 'orbit', detail: 'audio orbit', info: 'Route to audio orbit' }
    ],

    // Pattern manipulation methods
    patternMethods: [
        { label: 'slow', detail: 'slow down', info: 'Slow pattern by factor. Example: .slow(2)' },
        { label: 'fast', detail: 'speed up', info: 'Speed up pattern by factor. Example: .fast(2)' },
        { label: 'hurry', detail: 'hurry pattern', info: 'Speed up without changing duration' },
        { label: 'rev', detail: 'reverse', info: 'Reverse pattern. Example: .rev()' },
        { label: 'iter', detail: 'iterate', info: 'Iterate through pattern subdivisions' },
        { label: 'ply', detail: 'repeat events', info: 'Repeat each event. Example: .ply(2)' },
        { label: 'every', detail: 'every nth', info: 'Apply function every n cycles. Example: .every(4, fast(2))' },
        { label: 'sometimes', detail: 'sometimes apply', info: 'Apply randomly 50% of the time' },
        { label: 'rarely', detail: 'rarely apply', info: 'Apply randomly 25% of the time' },
        { label: 'often', detail: 'often apply', info: 'Apply randomly 75% of the time' },
        { label: 'almostAlways', detail: 'almost always', info: 'Apply 90% of the time' },
        { label: 'struct', detail: 'structure', info: 'Apply rhythmic structure. Example: .struct("x ~ x ~")' },
        { label: 'mask', detail: 'mask pattern', info: 'Mask pattern with binary. Example: .mask("1 0 1 0")' },
        { label: 'euclid', detail: 'euclidean', info: 'Euclidean rhythm. Example: .euclid(3, 8)' },
        { label: 'when', detail: 'conditional', info: 'Apply when condition is true' },
        { label: 'off', detail: 'offset copy', info: 'Offset and layer. Example: .off(0.125, x=>x.gain(0.5))' },
        { label: 'jux', detail: 'juxtapose', info: 'Pan copies left/right' },
        { label: 'degrade', detail: 'random drop', info: 'Randomly drop events' },
        { label: 'chop', detail: 'chop sample', info: 'Chop sample into pieces' },
        { label: 'slice', detail: 'slice sample', info: 'Slice sample by index' },
        { label: 'range', detail: 'scale range', info: 'Scale values to range. Example: .range(0.5, 1)' },
        { label: 'segment', detail: 'segment', info: 'Segment pattern. Example: .segment(4)' },
        { label: 'chunk', detail: 'chunk pattern', info: 'Apply function to chunks' },
        { label: 'add', detail: 'add values', info: 'Add to pattern values' },
        { label: 'sub', detail: 'subtract', info: 'Subtract from pattern values' },
        { label: 'mul', detail: 'multiply', info: 'Multiply pattern values' },
        { label: 'div', detail: 'divide', info: 'Divide pattern values' },
        { label: 'set', detail: 'set values', info: 'Set pattern values' },
        { label: 'pick', detail: 'pick from list', info: 'Pick from list of patterns' },
        { label: 'pickRestart', detail: 'pick (restart)', info: 'Pick and restart. Example: .pickRestart({...})' },
        { label: 'pickOut', detail: 'pick and resolve', info: 'Pick and resolve from object' },
        { label: 'early', detail: 'shift early', info: 'Shift pattern earlier in time' },
        { label: 'late', detail: 'shift late', info: 'Shift pattern later in time' },
        { label: 'offset', detail: 'time offset', info: 'Offset pattern in time' },
        { label: 'scramble', detail: 'random slices', info: 'Slice and play parts at random. Example: .scramble(4)' },
        { label: 'shuffle', detail: 'shuffle slices', info: 'Slice and play in random order. Example: .shuffle(4)' },
        { label: 'press', detail: 'syncopate', info: 'Shift events halfway into timespan' },
        { label: 'pressBy', detail: 'syncopate by', info: 'Shift events by amount. Example: .pressBy(0.5)' },
        { label: 'squeeze', detail: 'pick & compress', info: 'Pick and compress to event duration' },
        { label: 'striate', detail: 'slice progressive', info: 'Cut sample into parts, play progressively' },
        { label: 'splice', detail: 'slice with speed', info: 'Like slice but changes playback speed' },
        { label: 'swing', detail: 'swing rhythm', info: 'Add swing. Example: .swing(4)' },
        { label: 'swingBy', detail: 'swing by amount', info: 'Add swing with amount. Example: .swingBy(1/3, 4)' },
        { label: 'zoom', detail: 'play portion', info: 'Play portion of pattern. Example: .zoom(0.25, 0.75)' },
        { label: 'within', detail: 'apply to part', info: 'Apply function to part. Example: .within(0, 0.5, rev)' },
        { label: 'superimpose', detail: 'layer function', info: 'Superimpose function result. Example: .superimpose(x=>x.add(2))' },
        { label: 'stut', detail: 'echo (deprecated)', info: 'Like echo. Example: .stut(3, .8, 1/6)' }
    ],

    // Voicing/harmony
    harmonyFunctions: [
        { label: 'voicing', detail: 'voice chords', info: 'Apply chord voicing' },
        { label: 'anchor', detail: 'anchor note', info: 'Set anchor note. Example: .anchor("c3")' },
        { label: 'dict', detail: 'chord dictionary', info: 'Set chord dictionary. Example: .dict("ireal")' },
        { label: 'inversion', detail: 'chord inversion', info: 'Set chord inversion' }
    ],

    // Generators/modulators
    generators: [
        { label: 'sine', detail: 'sine wave', info: 'Sine wave modulator. Example: sine.range(0, 1)' },
        { label: 'saw', detail: 'saw wave', info: 'Sawtooth wave modulator' },
        { label: 'square', detail: 'square wave', info: 'Square wave modulator' },
        { label: 'tri', detail: 'triangle wave', info: 'Triangle wave modulator' },
        { label: 'rand', detail: 'random', info: 'Random values. Example: rand.range(0, 1)' },
        { label: 'irand', detail: 'random int', info: 'Random integers' },
        { label: 'perlin', detail: 'perlin noise', info: 'Smooth random. Example: perlin.range(0.5, 1)' },
        { label: 'time', detail: 'time value', info: 'Current time value' }
    ],

    // Keywords
    keywords: [
        { label: 'stack', detail: 'stack patterns', info: 'Layer multiple patterns. Example: stack(pat1, pat2)' },
        { label: 'cat', detail: 'concatenate', info: 'Concatenate patterns, one per cycle. Example: cat("e5", "b4")' },
        { label: 'slowcat', detail: 'concatenate slow', info: 'Synonym for cat' },
        { label: 'seq', detail: 'sequence', info: 'Like fastcat. Example: seq("e5", "b4", ["d5", "c5"])' },
        { label: 'sequence', detail: 'sequence', info: 'Same as seq/fastcat' },
        { label: 'sequenceP', detail: 'pattern of lists', info: 'Takes list of patterns, returns pattern of lists' },
        { label: 'timeCat', detail: 'timed concat', info: 'Concat with proportional steps. Example: timeCat([3,"e3"],[1,"g3"])' },
        { label: 'all', detail: 'apply to all', info: 'Apply function to all patterns' },
        { label: 'setcps', detail: 'set tempo', info: 'Set cycles per second. Example: setcps(0.75)' },
        { label: 'setbpm', detail: 'set BPM', info: 'Set beats per minute. Example: setbpm(120)' },
        { label: 'samples', detail: 'load samples', info: 'Load external samples. Example: samples("github:user/repo")' },
        { label: 'setDefaultVoicings', detail: 'default voicings', info: 'Set default chord voicings' },
        { label: 'register', detail: 'register function', info: 'Register custom function' }
    ],

    // Common sample banks
    sampleBanks: [
        { label: 'RhodeChords', detail: 'sample bank', info: 'Rhodes electric piano chords' },
        { label: 'RolandTR808', detail: 'sample bank', info: 'Classic TR-808 drum machine' },
        { label: 'RolandTR909', detail: 'sample bank', info: 'Classic TR-909 drum machine' },
        { label: 'tr808', detail: 'sample bank', info: 'TR-808 drums' },
        { label: 'tr909', detail: 'sample bank', info: 'TR-909 drums' },
        { label: 'Linn9000', detail: 'sample bank', info: 'LinnDrum samples' },
        { label: 'RolandMT32', detail: 'sample bank', info: 'MT-32 samples' }
    ],

    // === EXPANDED FUNCTIONS FROM API REFERENCE ===

    additionalEffects: [
        { label: 'adsr', detail: 'function', info: 'ADSR envelope: Combination of Attack, Decay, Sustain, and Release. time : number | Pattern - attack time in seconds time' },
        { label: 'amp', detail: 'function', info: 'Like gain, but linear.' },
        { label: 'appLeft', detail: 'function', info: 'As with appBoth, but the whole timespan is not the intersection, but the timespan from the function of patterns that thi' },
        { label: 'appRight', detail: 'function', info: 'As with appLeft, but whole timespans are instead taken from the pattern of values, i.e. structure is preserved from the' },
        { label: 'applyGradualLowpass', detail: 'function', info: 'Applies a constantly changing lowpass filter to the given sound. input : AudioBuffer lpFreqStart : number lpFreqEnd : nu' },
        { label: 'asym', detail: 'function', info: 'Asymmetrical diode distortion distortion : number | Pattern - amount of distortion to apply volume : number | Pattern -' },
        { label: 'att', detail: 'function', info: 'Amplitude envelope attack time: Specifies how long it takes for the sound to reach its peak value, relative to the onset' },
        { label: 'bandf', detail: 'function', info: 'Sets the center frequency of the band-pass filter. When using mininotation, you can also optionally supply the "bpq" par' },
        { label: 'bandq', detail: 'function', info: 'Sets the band-pass q-factor (resonance). q : number | Pattern - q factor' },
        { label: 'bp', detail: 'function', info: 'Sets the center frequency of the band-pass filter. When using mininotation, you can also optionally supply the "bpq" par' },
        { label: 'bpa', detail: 'function', info: 'Sets the attack duration for the bandpass filter envelope. attack : number | Pattern - time of the bandpass filter envel' },
        { label: 'bpattack', detail: 'function', info: 'Sets the attack duration for the bandpass filter envelope. attack : number | Pattern - time of the bandpass filter envel' },
        { label: 'bpd', detail: 'function', info: 'Sets the decay duration for the bandpass filter envelope. decay : number | Pattern - time of the bandpass filter envelop' },
        { label: 'bpdecay', detail: 'function', info: 'Sets the decay duration for the bandpass filter envelope. decay : number | Pattern - time of the bandpass filter envelop' },
        { label: 'bpe', detail: 'function', info: 'Sets the bandpass filter envelope modulation depth. modulation : number | Pattern - depth of the bandpass filter envelop' },
        { label: 'bpenv', detail: 'function', info: 'Sets the bandpass filter envelope modulation depth. modulation : number | Pattern - depth of the bandpass filter envelop' },
        { label: 'bpf', detail: 'function', info: 'Sets the center frequency of the band-pass filter. When using mininotation, you can also optionally supply the "bpq" par' },
        { label: 'bpq', detail: 'function', info: 'Sets the band-pass q-factor (resonance). q : number | Pattern - q factor' },
        { label: 'bpr', detail: 'function', info: 'Sets the release time for the bandpass filter envelope. release : number | Pattern - time of the bandpass filter envelop' },
        { label: 'bprelease', detail: 'function', info: 'Sets the release time for the bandpass filter envelope. release : number | Pattern - time of the bandpass filter envelop' },
        { label: 'bps', detail: 'function', info: 'Sets the sustain amplitude for the bandpass filter envelope. sustain : number | Pattern - amplitude of the bandpass filt' },
        { label: 'bpsustain', detail: 'function', info: 'Sets the sustain amplitude for the bandpass filter envelope. sustain : number | Pattern - amplitude of the bandpass filt' },
        { label: 'chebyshev', detail: 'function', info: 'Distortion via Chebyshev polynomials distortion : number | Pattern - amount of distortion to apply volume : number | Pat' },
        { label: 'compress', detail: 'function', info: 'Compress each cycle into the given timespan, leaving a gap cat( s("bd sd").compress(.25,.75), s("~ bd sd ~") )' },
        { label: 'compressor', detail: 'function', info: 'Dynamics Compressor. The params are compressor("threshold:ratio:knee:attack:release") More info here .compressor("-20:20' },
        { label: 'ctf', detail: 'function', info: 'Applies the cutoff frequency of the low-pass filter. When using mininotation, you can also optionally add the "lpq" para' },
        { label: 'cubic', detail: 'function', info: 'Cubic polynomial distortion distortion : number | Pattern - amount of distortion to apply volume : number | Pattern - li' },
        { label: 'cutoff', detail: 'function', info: 'Applies the cutoff frequency of the low-pass filter. When using mininotation, you can also optionally add the "lpq" para' },
        { label: 'dec', detail: 'function', info: 'Amplitude envelope decay time: the time it takes after the attack time to reach the sustain level. Note that the decay i' },
        { label: 'defaultmidimap', detail: 'function', info: 'configures the default midimap, which is used when no "midimap" port is set defaultmidimap({ lpf: 74 }) $: note("c a f e' },
        { label: 'delayfb', detail: 'function', info: 'Sets the level of the signal that is fed back into the delay. Caution: Values >= 1 will result in a signal that gets lou' },
        { label: 'delayfeedback', detail: 'function', info: 'Sets the level of the signal that is fed back into the delay. Caution: Values >= 1 will result in a signal that gets lou' },
        { label: 'delayspeed', detail: 'function', info: 'Sets the time of the delay effect. delayspeed : number | Pattern - controls the pitch of the delay feedback note("d d a#' },
        { label: 'delaysync', detail: 'function', info: 'Sets the time of the delay effect in cycles. cycles : number | Pattern - delay length in cycles' },
        { label: 'delayt', detail: 'function', info: 'Sets the time of the delay effect. delayspeed : number | Pattern - controls the pitch of the delay feedback note("d d a#' },
        { label: 'dfb', detail: 'function', info: 'Sets the level of the signal that is fed back into the delay. Caution: Values >= 1 will result in a signal that gets lou' },
        { label: 'diode', detail: 'function', info: 'Diode-emulating distortion distortion : number | Pattern - amount of distortion to apply volume : number | Pattern - lin' },
        { label: 'discreteOnly', detail: 'function', info: 'Returns a new pattern, with "continuous" haps (those without "whole" timespans) removed from query results.' },
        { label: 'dist', detail: 'function', info: 'Wave shaping distortion. CAUTION: it can get loud. Second option in optional array syntax (ex: ".9:.5") applies a postga' },
        { label: 'distort', detail: 'function', info: 'Wave shaping distortion. CAUTION: it can get loud. Second option in optional array syntax (ex: ".9:.5") applies a postga' },
        { label: 'distorttype', detail: 'function', info: 'Type of waveshaping distortion to apply. type : number | string | Pattern - type of distortion to apply .penv(24).pdecay' },
        { label: 'distortvol', detail: 'function', info: 'Postgain for waveshaping distortion. volume : number | Pattern - linear postgain of the distortion' },
        { label: 'disttype', detail: 'function', info: 'Type of waveshaping distortion to apply. type : number | string | Pattern - type of distortion to apply .penv(24).pdecay' },
        { label: 'distvol', detail: 'function', info: 'Postgain for waveshaping distortion. volume : number | Pattern - linear postgain of the distortion' },
        { label: 'djf', detail: 'function', info: 'DJ filter, below 0.5 is low pass filter, above is high pass filter. cutoff : number | Pattern - below 0.5 is low pass fi' },
        { label: 'drawLine', detail: 'function', info: 'Intended for a debugging, drawLine renders the pattern as a string, where each character represents the same time span.' },
        { label: 'drive', detail: 'function', info: 'Filter overdrive for supported filter types note("{f g g c d a a#}%16".sub(17)).s("supersaw").lpenv(8).lpf(150).lpq(.8).' },
        { label: 'dry', detail: 'function', info: 'Set dryness of reverb. See room and size for more information about reverb. dry : number | Pattern - 0 = wet, 1 = dry' },
        { label: 'dt', detail: 'function', info: 'Sets the time of the delay effect. delayspeed : number | Pattern - controls the pitch of the delay feedback note("d d a#' },
        { label: 'fanchor', detail: 'function', info: 'controls the center of the filter envelope. 0 is unipolar positive, .5 is bipolar, 1 is unipolar negative center : numbe' },
        { label: 'filter', detail: 'function', info: 'Filters haps using the given function test : function - function to test Hap' },
        { label: 'filterHaps', detail: 'function', info: 'Returns a new Pattern, which only returns haps that meet the given test. hap_test : function - a function which returns' },
        { label: 'filterValues', detail: 'function', info: 'As with filterHaps, but the function is applied to values inside haps. value_test : function' },
        { label: 'filterWhen', detail: 'function', info: 'Filters haps by their begin time test : function - function to test Hap.whole.begin' },
        { label: 'fmattack', detail: 'function', info: 'Attack time for the FM envelope: time it takes to reach maximum modulation time : number | Pattern - attack time note("c' },
        { label: 'fmdecay', detail: 'function', info: 'Decay time for the FM envelope: seconds until the sustain level is reached after the attack phase. time : number | Patte' },
        { label: 'fmenv', detail: 'function', info: 'Ramp type of fm envelope. Exp might be a bit broken.. type : number | Pattern - lin | exp note("c e g b g e") .fm(4) .fm' },
        { label: 'fmsustain', detail: 'function', info: 'Sustain level for the FM envelope: how much modulation is applied after the decay phase level : number | Pattern - susta' },
        { label: 'focus', detail: 'function', info: 'Similar to compress, but doesn"t leave gaps, and the "focus" can be bigger than a cycle' },
        { label: 'fold', detail: 'function', info: 'Wavefolding distortion distortion : number | Pattern - amount of distortion to apply volume : number | Pattern - linear' },
        { label: 'ftype', detail: 'function', info: 'Sets the filter type. The ladder filter is more aggressive. More types might be added in the future. type : number | Pat' },
        { label: 'generateReverb', detail: 'function', info: 'Generates a reverb impulse response. params : Object - TODO: Document the properties. callback : function - Function to' },
        { label: 'hard', detail: 'function', info: 'Hard-clipping distortion distortion : number | Pattern - amount of distortion to apply volume : number | Pattern - linea' },
        { label: 'hcutoff', detail: 'function', info: 'Applies the cutoff frequency of the high-pass filter. When using mininotation, you can also optionally add the "hpq" par' },
        { label: 'hp', detail: 'function', info: 'Applies the cutoff frequency of the high-pass filter. When using mininotation, you can also optionally add the "hpq" par' },
        { label: 'hpa', detail: 'function', info: 'Sets the attack duration for the highpass filter envelope. attack : number | Pattern - time of the highpass filter envel' },
        { label: 'hpattack', detail: 'function', info: 'Sets the attack duration for the highpass filter envelope. attack : number | Pattern - time of the highpass filter envel' },
        { label: 'hpd', detail: 'function', info: 'Sets the decay duration for the highpass filter envelope. decay : number | Pattern - time of the highpass filter envelop' },
        { label: 'hpdecay', detail: 'function', info: 'Sets the decay duration for the highpass filter envelope. decay : number | Pattern - time of the highpass filter envelop' },
        { label: 'hpe', detail: 'function', info: 'Sets the highpass filter envelope modulation depth. modulation : number | Pattern - depth of the highpass filter envelop' },
        { label: 'hpenv', detail: 'function', info: 'Sets the highpass filter envelope modulation depth. modulation : number | Pattern - depth of the highpass filter envelop' },
        { label: 'hpr', detail: 'function', info: 'Sets the release time for the highpass filter envelope. release : number | Pattern - time of the highpass filter envelop' },
        { label: 'hprelease', detail: 'function', info: 'Sets the release time for the highpass filter envelope. release : number | Pattern - time of the highpass filter envelop' },
        { label: 'hps', detail: 'function', info: 'Sets the sustain amplitude for the highpass filter envelope. sustain : number | Pattern - amplitude of the highpass filt' },
        { label: 'hpsustain', detail: 'function', info: 'Sets the sustain amplitude for the highpass filter envelope. sustain : number | Pattern - amplitude of the highpass filt' },
        { label: 'hresonance', detail: 'function', info: 'Controls the high-pass q-value. q : number | Pattern - resonance factor between 0 and 50' },
        { label: 'ir', detail: 'function', info: 'Sets the sample to use as an impulse response for the reverb. sample : string | Pattern - to use as an impulse response' },
        { label: 'iresponse', detail: 'function', info: 'Sets the sample to use as an impulse response for the reverb. sample : string | Pattern - to use as an impulse response' },
        { label: 'leslie', detail: 'function', info: 'Emulation of a Leslie speaker: speakers rotating in a wooden amplified cabinet. wet : number | Pattern - between 0 and 1' },
        { label: 'lock', detail: 'function', info: 'Specifies whether delaytime is calculated relative to cps. enable : number | Pattern - When set to 1, delaytime is a dir' },
        { label: 'lp', detail: 'function', info: 'Applies the cutoff frequency of the low-pass filter. When using mininotation, you can also optionally add the "lpq" para' },
        { label: 'lpa', detail: 'function', info: 'Sets the attack duration for the lowpass filter envelope. attack : number | Pattern - time of the filter envelope note("' },
        { label: 'lpattack', detail: 'function', info: 'Sets the attack duration for the lowpass filter envelope. attack : number | Pattern - time of the filter envelope note("' },
        { label: 'lpd', detail: 'function', info: 'Sets the decay duration for the lowpass filter envelope. decay : number | Pattern - time of the filter envelope note("c2' },
        { label: 'lpdecay', detail: 'function', info: 'Sets the decay duration for the lowpass filter envelope. decay : number | Pattern - time of the filter envelope note("c2' },
        { label: 'lpe', detail: 'function', info: 'Sets the lowpass filter envelope modulation depth. modulation : number | Pattern - depth of the lowpass filter envelope' },
        { label: 'lpenv', detail: 'function', info: 'Sets the lowpass filter envelope modulation depth. modulation : number | Pattern - depth of the lowpass filter envelope' },
        { label: 'lpr', detail: 'function', info: 'Sets the release time for the lowpass filter envelope. release : number | Pattern - time of the filter envelope note("c2' },
        { label: 'lprelease', detail: 'function', info: 'Sets the release time for the lowpass filter envelope. release : number | Pattern - time of the filter envelope note("c2' },
        { label: 'lps', detail: 'function', info: 'Sets the sustain amplitude for the lowpass filter envelope. sustain : number | Pattern - amplitude of the lowpass filter' },
        { label: 'lpsustain', detail: 'function', info: 'Sets the sustain amplitude for the lowpass filter envelope. sustain : number | Pattern - amplitude of the lowpass filter' },
        { label: 'lrate', detail: 'function', info: 'Rate of modulation / rotation for leslie effect rate : number | Pattern - 6.7 for fast, 0.7 for slow' },
        { label: 'midimaps', detail: 'function', info: 'Adds midimaps to the registry. Inside each midimap, control names (e.g. lpf) are mapped to cc numbers. midimaps({ mymap:' },
        { label: 'onsetsOnly', detail: 'function', info: 'Returns a new pattern, with all haps without onsets filtered out. A hap with an onset is one with a whole timespan that' },
        { label: 'panchor', detail: 'function', info: 'Sets the range anchor of the envelope: anchor 0: range = [note, note + penv] anchor 1: range = [note - penv, note] If yo' },
        { label: 'patt', detail: 'function', info: 'Attack time of pitch envelope. time : number | Pattern - time in seconds note("c eb g bb").pattack("0 .1 .25 .5").slow(2' },
        { label: 'pattack', detail: 'function', info: 'Attack time of pitch envelope. time : number | Pattern - time in seconds note("c eb g bb").pattack("0 .1 .25 .5").slow(2' },
        { label: 'pcurve', detail: 'function', info: 'Curve of envelope. Defaults to linear. exponential is good for kicks type : number | Pattern - 0 = linear, 1 = exponenti' },
        { label: 'pdec', detail: 'function', info: 'Decay time of pitch envelope. time : number | Pattern - time in seconds note("<c eb g bb>").pdecay("<0 .1 .25 .5>")' },
        { label: 'pdecay', detail: 'function', info: 'Decay time of pitch envelope. time : number | Pattern - time in seconds note("<c eb g bb>").pdecay("<0 .1 .25 .5>")' }
    ],

    additionalPatternmethods: [
        { label: 'Experimental', detail: 'function', info: '"zips" together the steps of the provided patterns. This can create a long repetition, taking place over a single, dense' },
        { label: 'Pattern', detail: 'function', info: 'Create a pattern. As an end user, you will most likely not create a Pattern directly. query : function - The function th' },
        { label: 'accelerate', detail: 'function', info: 'A pattern of numbers that speed up (or slow down) samples while they play. Currently only supported by osc / superdirt.' },
        { label: 'allTransforms', detail: 'function', info: 'Applies a function to all the running patterns. Note that the patterns are groups together into a single stack before th' },
        { label: 'almostNever', detail: 'function', info: 'Shorthand for .sometimesBy(0.1, fn)' },
        { label: 'always', detail: 'function', info: 'Shorthand for .sometimesBy(1, fn) (always calls fn)' },
        { label: 'appBoth', detail: 'function', info: 'When this method is called on a pattern of functions, it matches its haps with those in the given pattern of values. A n' },
        { label: 'appWhole', detail: 'function', info: 'Assumes "this" is a pattern of functions, and given a function to resolve wholes, applies a given pattern of values to t' },
        { label: 'apply', detail: 'function', info: 'Like layer, but with a single function: "<c3 eb3 g3>".scale("C minor").apply(scaleTranspose("0,2,4")).note()' },
        { label: 'applyHannWindow', detail: 'function', info: 'Apply Hann window in-place' },
        { label: 'arp', detail: 'function', info: 'Selects indices in in stacked notes. note("<[c,eb,g]!2 [c,f,ab] [d,f,ab]>") .arp("0 [0,2] 1 [0,2]")' },
        { label: 'arpWith', detail: 'function', info: 'Selects indices in in stacked notes. note("<[c,eb,g]!2 [c,f,ab] [d,f,ab]>") .arpWith(haps => haps[2])' },
        { label: 'arrange', detail: 'function', info: 'Allows to arrange multiple patterns together over multiple cycles. Takes a variable number of arrays with two elements s' },
        { label: 'bbexpr', detail: 'function', info: 'Create byte beats with custom expressions byteBeatExpression : number | Pattern - bitwise expression for creating bytebe' },
        { label: 'bbst', detail: 'function', info: 'Create byte beats with custom expressions byteBeatStartTime : number | Pattern - in samples (t) note("c3!8".add("{0 0 12' },
        { label: 'begin', detail: 'function', info: 'A pattern of numbers from 0 to 1. Skips the beginning of each sample, e.g. 0.25 to cut off the first quarter from each s' },
        { label: 'berlin', detail: 'function', info: 'Generates a continuous pattern of [berlin noise](conceived by Jame Coyne and Jade Rowland as a joke but turned out to be' },
        { label: 'binary', detail: 'function', info: 'Creates a pattern from a binary number. n : number - input number to convert to binary "hh".s().struct(binary(5)) // "hh' },
        { label: 'binaryN', detail: 'function', info: 'Creates a pattern from a binary number, padded to n bits long. n : number - input number to convert to binary nBits : nu' },
        { label: 'bite', detail: 'function', info: 'Splits a pattern into the given number of slices, and plays them according to a pattern of slice numbers. Similar to sli' },
        { label: 'brak', detail: 'function', info: 'Returns a new pattern where every other cycle is played once, twice as fast, and offset in time by one quarter of a cycl' },
        { label: 'brand', detail: 'function', info: 'A continuous pattern of 0 or 1 (binary random)' },
        { label: 'brandBy', detail: 'function', info: 'A continuous pattern of 0 or 1 (binary random), with a probability for the value being 1 probability : number - a number' },
        { label: 'byteBeatExpression', detail: 'function', info: 'Create byte beats with custom expressions byteBeatExpression : number | Pattern - bitwise expression for creating bytebe' },
        { label: 'byteBeatStartTime', detail: 'function', info: 'Create byte beats with custom expressions byteBeatStartTime : number | Pattern - in samples (t) note("c3!8".add("{0 0 12' },
        { label: 'ccn', detail: 'function', info: 'MIDI control number: Sends a MIDI control change message. MIDI : number | Pattern - control number (0-127)' },
        { label: 'ccv', detail: 'function', info: 'MIDI control value: Sends a MIDI control change message. MIDI : number | Pattern - control value (0-127)' },
        { label: 'ceil', detail: 'function', info: 'Assumes a numerical pattern. Returns a new pattern with all values set to their mathematical ceiling. E.g. 3.2 replaced' },
        { label: 'ch', detail: 'function', info: 'Allows you to set the output channels on the interface channels : number | Pattern - pattern the output channels note("e' },
        { label: 'channel', detail: 'function', info: 'Choose the channel the pattern is sent to in superdirt channel : number | Pattern - channel number' },
        { label: 'channels', detail: 'function', info: 'Allows you to set the output channels on the interface channels : number | Pattern - pattern the output channels note("e' },
        { label: 'choose', detail: 'function', info: 'Chooses from the given list of values (or patterns of values), according to the pattern that the method is called on. Th' },
        { label: 'choose2', detail: 'function', info: 'As with choose, but the pattern that this method is called on should be in the range -1 .. 1 xs : any' },
        { label: 'chooseCycles', detail: 'function', info: 'Picks one of the elements at random each cycle. chooseCycles("bd", "hh", "sd").s().fast(8)' },
        { label: 'chooseInWith', detail: 'function', info: 'As with {chooseWith}, but the structure comes from the chosen values, rather than the pattern you"re using to choose wit' },
        { label: 'chooseWith', detail: 'function', info: 'Choose from the list of values (or patterns of values) using the given pattern of numbers, which should be in the range' },
        { label: 'chorus', detail: 'function', info: 'mix control for the chorus effect chorus : string | Pattern - mix amount between 0 and 1 note("d d a# a").s("sawtooth").' },
        { label: 'chunkBack', detail: 'function', info: 'Like chunk, but cycles through the parts in reverse order. Known as chunk" in tidalcycles "0 1 2 3".chunkBack(4, x=>x.ad' },
        { label: 'chunkBackInto', detail: 'function', info: 'Like chunkInto, but moves backwards through the chunks. .bank("tr909")' },
        { label: 'chunkInto', detail: 'function', info: 'Like chunk, but the function is applied to a looped subcycle of the source pattern. .bank("tr909")' },
        { label: 'chunkback', detail: 'function', info: 'Like chunk, but cycles through the parts in reverse order. Known as chunk" in tidalcycles "0 1 2 3".chunkBack(4, x=>x.ad' },
        { label: 'chunkbackinto', detail: 'function', info: 'Like chunkInto, but moves backwards through the chunks. .bank("tr909")' },
        { label: 'chunkinto', detail: 'function', info: 'Like chunk, but the function is applied to a looped subcycle of the source pattern. .bank("tr909")' },
        { label: 'control', detail: 'function', info: 'MIDI control: Sends a MIDI control change message. MIDI : number | Pattern - control number (0-127) MIDI : number | Patt' },
        { label: 'cpm', detail: 'function', info: 'Plays the pattern at the given cycles per minute.' },
        { label: 'degradeBy', detail: 'function', info: 'Randomly removes events from the pattern by a given amount. 0 = 0% chance of removal 1 = 100% chance of removal //beat g' },
        { label: 'density', detail: 'function', info: 'Speed up a pattern by the given factor. Used by "*" in mini notation. factor : number | Pattern - speed up factor' },
        { label: 'det', detail: 'function', info: 'Set detune for stacked voices of supported oscillators note("d f a a# a d3").fast(2).s("supersaw").detune("<.1 .2 .5 24.' },
        { label: 'detune', detail: 'function', info: 'Set detune for stacked voices of supported oscillators note("d f a a# a d3").fast(2).s("supersaw").detune("<.1 .2 .5 24.' },
        { label: 'each', detail: 'function', info: 'Applies a function to each of the running patterns separately. This is intended for future use with upcoming "stepwise"' },
        { label: 'echoWith', detail: 'function', info: 'Superimpose and offset multiple times, applying the given function each time. times : number - how many times to repeat' },
        { label: 'echowith', detail: 'function', info: 'Superimpose and offset multiple times, applying the given function each time. times : number - how many times to repeat' },
        { label: 'eish', detail: 'function', info: 'A "euclid" variant with an additional parameter that morphs the resulting rhythm from 0 (no morphing) to 1 (completely "' },
        { label: 'end', detail: 'function', info: 'The same as .begin, but cuts off the end off each sample. length : number | Pattern - 1 = whole sample, .5 = half sample' },
        { label: 'euclidLegato', detail: 'function', info: 'Similar to euclid, but each pulse is held until the next pulse, so there will be no gaps. pulses : number - the number o' },
        { label: 'euclidLegatoRot', detail: 'function', info: 'Similar to euclid, but each pulse is held until the next pulse, so there will be no gaps, and has an additional paramete' },
        { label: 'euclidRot', detail: 'function', info: 'Like euclid, but has an additional parameter for "rotating" the resulting sequence. pulses : number - the number of onse' },
        { label: 'euclidish', detail: 'function', info: 'A "euclid" variant with an additional parameter that morphs the resulting rhythm from 0 (no morphing) to 1 (completely "' },
        { label: 'fastChunk', detail: 'function', info: 'Like chunk, but the cycles of the source pattern aren"t repeated for each set of chunks. "<0 8> 1 2 3 4 5 6 7" .scale("C' },
        { label: 'fastGap', detail: 'function', info: 'speeds up a pattern like fast, but rather than it playing multiple times as fast would it instead leaves a gap in the re' },
        { label: 'fastcat', detail: 'function', info: 'Like cat, but the items are crammed into one cycle. seq("e5", "b4", ["d5", "c5"]).note() // "e5 b4 [d5 c5]".note() // As' },
        { label: 'fastchunk', detail: 'function', info: 'Like chunk, but the cycles of the source pattern aren"t repeated for each set of chunks. "<0 8> 1 2 3 4 5 6 7" .scale("C' },
        { label: 'fastgap', detail: 'function', info: 'speeds up a pattern like fast, but rather than it playing multiple times as fast would it instead leaves a gap in the re' },
        { label: 'firstCycle', detail: 'function', info: 'Queries the pattern for the first cycle, returning Haps. Mainly of use when debugging a pattern. with_context : Boolean' },
        { label: 'firstOf', detail: 'function', info: 'Applies the given function every n cycles, starting from the first cycle. n : number - how many cycles func : function -' },
        { label: 'floor', detail: 'function', info: 'Assumes a numerical pattern. Returns a new pattern with all values set to their mathematical floor. E.g. 3.7 replaced wi' },
        { label: 'fmwave', detail: 'function', info: 'Waveform of the fm modulator wave : number | Pattern - waveform' },
        { label: 'freq', detail: 'function', info: 'Set frequency of sound. frequency : number | Pattern - in Hz. the audible range is between 20 and 20000 Hz freq("220 110' },
        { label: 'fromBipolar', detail: 'function', info: 'Assumes a numerical pattern, containing bipolar values in the range -1 .. 1 Returns a new pattern with values scaled to' },
        { label: 'hush', detail: 'function', info: 'Silences a pattern. stack( s("bd").hush(), s("hh*3") )' },
        { label: 'inhabit', detail: 'function', info: 'Picks patterns (or plain values) either from a list (by index) or a lookup table (by name). Similar to pick, but cycles' },
        { label: 'into', detail: 'function', info: 'Breaks a pattern into pieces according to the structure of a given pattern. True values in the given pattern cause the c' },
        { label: 'inv', detail: 'function', info: 'Swaps 1s and 0s in a binary pattern.' },
        { label: 'invert', detail: 'function', info: 'Swaps 1s and 0s in a binary pattern.' },
        { label: 'irbegin', detail: 'function', info: 'Sets the beginning of the IR response sample begin : string | Pattern - between 0 and 1 samples("github:switchangel/pad"' },
        { label: 'irspeed', detail: 'function', info: 'Sets speed of the sample for the impulse response. speed : string | Pattern samples("github:switchangel/pad") $: s("brk/' },
        { label: 'isaw', detail: 'function', info: 'A sawtooth signal between 1 and 0 (like saw, but flipped). note("<c3 [eb3,g3] g2 [g3,bb3]>*8") .clip(isaw.slow(2)) .scal' },
        { label: 'iterBack', detail: 'function', info: 'Like iter, but plays the subdivisions in reverse order. Known as iter" in tidalcycles note("0 1 2 3".scale("A minor")).i' },
        { label: 'iterback', detail: 'function', info: 'Like iter, but plays the subdivisions in reverse order. Known as iter" in tidalcycles note("0 1 2 3".scale("A minor")).i' },
        { label: 'juxBy', detail: 'function', info: 'Jux with adjustable stereo width. 0 = mono, 1 = full stereo.' },
        { label: 'juxby', detail: 'function', info: 'Jux with adjustable stereo width. 0 = mono, 1 = full stereo.' },
        { label: 'lastOf', detail: 'function', info: 'Applies the given function every n cycles, starting from the last cycle. n : number - how many cycles func : function -' },
        { label: 'layer', detail: 'function', info: 'Layers the result of the given function(s). Like superimpose, but without the original pattern: "<0 2 4 6 ~ 4 ~ 2 0!3 ~!' },
        { label: 'linger', detail: 'function', info: 'Selects the given fraction of the pattern and repeats that part to fill the remainder of the cycle. fraction : number -' },
        { label: 'midibend', detail: 'function', info: 'MIDI pitch bend: Sends a MIDI pitch bend message. midibend : number | Pattern - MIDI pitch bend (-1 - 1) note("c4").midi' },
        { label: 'midichan', detail: 'function', info: 'MIDI channel: Sets the MIDI channel for the event. channel : number | Pattern - MIDI channel number (0-15) note("c4").mi' },
        { label: 'midicmd', detail: 'function', info: 'MIDI command: Sends a MIDI command message. command : number | Pattern - MIDI command midicmd("clock*48,<start stop>/2")' },
        { label: 'midiport', detail: 'function', info: 'MIDI port: Sets the MIDI port for the event. port : number | Pattern - MIDI port note("c a f e").midiport("<0 1 2 3>").m' },
        { label: 'miditouch', detail: 'function', info: 'MIDI key after touch: Sends a MIDI key after touch message. miditouch : number | Pattern - MIDI key after touch (0-1) no' },
        { label: 'never', detail: 'function', info: 'Shorthand for .sometimesBy(0, fn) (never calls fn)' },
        { label: 'noise', detail: 'function', info: 'Adds pink noise to the mix wet : number | Pattern - wet amount' },
        { label: 'octave', detail: 'function', info: 'Sets the default octave of a synth. octave : number | Pattern - octave number' },
        { label: 'oschost', detail: 'function', info: 'The host to send open sound control messages to. Requires running the OSC bridge. oschost : string | Pattern - e.g. "loc' },
        { label: 'oscport', detail: 'function', info: 'The port to send open sound control messages to. Requires running the OSC bridge. oscport : number | Pattern - e.g. 5712' },
        { label: 'palindrome', detail: 'function', info: 'Applies rev to a pattern every other cycle, so that the pattern alternates between forwards and backwards. note("c d e g' },
        { label: 'pianoroll', detail: 'function', info: 'Visualises a pattern as a scrolling "pianoroll", displayed in the background of the editor. To show a pianoroll for all' },
        { label: 'pickF', detail: 'function', info: 'pickF lets you use a pattern of numbers to pick which function to apply to another pattern. pat : Pattern lookup : Patte' },
        { label: 'pickReset', detail: 'function', info: 'Similar to pick, but the choosen pattern is reset when its index is triggered. pat : Pattern xs : *' }
    ],

    additionalGenerators: [
        { label: 'computeMagnitudes', detail: 'function', info: 'Compute squared magnitudes for peak finding' },
        { label: 'cosine', detail: 'function', info: 'A cosine signal between 0 and 1. .scale("C:minor")' },
        { label: 'cosine2', detail: 'function', info: 'A cosine signal between -1 and 1 (like cosine, but bipolar).' },
        { label: 'fscope', detail: 'function', info: 'Renders an oscilloscope for the frequency domain of the audio signal. color : string - line color as hex or color name.' },
        { label: 'isaw2', detail: 'function', info: 'A sawtooth signal between 1 and -1 (like saw2, but flipped).' },
        { label: 'itri', detail: 'function', info: 'An inverted triangle signal between 1 and 0 (like tri, but flipped).' },
        { label: 'itri2', detail: 'function', info: 'An inverted triangle signal between -1 and 1 (like itri, but bipolar).' },
        { label: 'osc', detail: 'function', info: 'Sends each hap as an OSC message, which can be picked up by SuperCollider or any other OSC-enabled software. For more in' },
        { label: 'repeatCycles', detail: 'function', info: 'Repeats each cycle the given number of times. note(irand(12).add(34)).segment(4).repeatCycles(2).s("gm_acoustic_guitar_n' },
        { label: 'saw2', detail: 'function', info: 'A sawtooth signal between -1 and 1 (like saw, but bipolar).' },
        { label: 'scope', detail: 'function', info: 'Renders an oscilloscope for the time domain of the audio signal. config : object - optional config with options: align :' },
        { label: 'sine2', detail: 'function', info: 'A sine signal between -1 and 1 (like sine, but bipolar).' },
        { label: 'square2', detail: 'function', info: 'A square signal between -1 and 1 (like square, but bipolar).' },
        { label: 'tables', detail: 'function', info: 'Loads a collection of wavetables to use with s' },
        { label: 'tri2', detail: 'function', info: 'A triangle signal between -1 and 1 (like tri, but bipolar).' },
        { label: 'tscope', detail: 'function', info: 'Renders an oscilloscope for the time domain of the audio signal. config : object - optional config with options: align :' },
        { label: 'wchoose', detail: 'function', info: 'Chooses randomly from the given list of elements by giving a probability to each element pairs : any - arrays of value a' },
        { label: 'wchooseCycles', detail: 'function', info: 'Picks one of the elements at random each cycle by giving a probability to each element wchooseCycles(["bd",10], ["hh",1]' }
    ],

    additionalOther: [
        { label: 'absOriA', detail: 'function', info: 'The device"s absolute orientation alpha value ranges from 0 to 1.' },
        { label: 'absOriB', detail: 'function', info: 'The device"s absolute orientation beta value ranges from 0 to 1.' },
        { label: 'absOriG', detail: 'function', info: 'The device"s absolute orientation gamma value ranges from 0 to 1.' },
        { label: 'absOriX', detail: 'function', info: 'The device"s absolute orientation beta value ranges from 0 to 1.' },
        { label: 'absOriY', detail: 'function', info: 'The device"s absolute orientation gamma value ranges from 0 to 1.' },
        { label: 'absOriZ', detail: 'function', info: 'The device"s absolute orientation alpha value ranges from 0 to 1.' },
        { label: 'absoluteOrientationBeta', detail: 'function', info: 'The device"s absolute orientation beta value ranges from 0 to 1.' },
        { label: 'absoluteOrientationGamma', detail: 'function', info: 'The device"s absolute orientation gamma value ranges from 0 to 1.' },
        { label: 'absoluteOrientationX', detail: 'function', info: 'The device"s absolute orientation beta value ranges from 0 to 1.' },
        { label: 'absoluteOrientationY', detail: 'function', info: 'The device"s absolute orientation gamma value ranges from 0 to 1.' },
        { label: 'absoluteOrientationZ', detail: 'function', info: 'The device"s absolute orientation alpha value ranges from 0 to 1.' },
        { label: 'accX', detail: 'function', info: 'The accelerometer"s x-axis value ranges from 0 to 1.' },
        { label: 'accY', detail: 'function', info: 'The accelerometer"s y-axis value ranges from 0 to 1.' },
        { label: 'accZ', detail: 'function', info: 'The accelerometer"s z-axis value ranges from 0 to 1.' },
        { label: 'accelerationX', detail: 'function', info: 'The accelerometer"s x-axis value ranges from 0 to 1.' },
        { label: 'accelerationY', detail: 'function', info: 'The accelerometer"s y-axis value ranges from 0 to 1.' },
        { label: 'accelerationZ', detail: 'function', info: 'The accelerometer"s z-axis value ranges from 0 to 1.' },
        { label: 'addVoicings', detail: 'function', info: 'Adds a new custom voicing dictionary. name : string - identifier for the voicing dictionary dictionary : Object - maps c' },
        { label: 'aliasBank', detail: 'function', info: 'Register an alias for a bank of sounds. Optionally accepts a single argument map of bank aliases. Optionally accepts a s' },
        { label: 'as', detail: 'function', info: 'Sets properties in a batch. mapping : String | Array - the control names that are set "c:.5 a:1 f:.25 e:.8".as("note:cli' },
        { label: 'chyx', detail: 'function', info: 'BYTE BEATS' },
        { label: 'clip', detail: 'function', info: 'Multiplies the duration with the given number. Also cuts samples off at the end if they exceed the duration. factor : nu' },
        { label: 'coarse', detail: 'function', info: 'Fake-resampling for lowering the sample rate. Caution: This effect seems to only work in chromium based browsers factor' },
        { label: 'color', detail: 'function', info: 'Sets the color of the hap in visualizations like pianoroll or highlighting. color : string - Hexadecimal or CSS color na' },
        { label: 'colour', detail: 'function', info: 'Sets the color of the hap in visualizations like pianoroll or highlighting. color : string - Hexadecimal or CSS color na' },
        { label: 'crossfade', detail: 'function', info: 'Equal Power Crossfade function. Smoothly transitions between signals A and B, maintaining consistent perceived loudness.' },
        { label: 'csoundm', detail: 'function', info: 'Sends notes to Csound for rendering with MIDI semantics. The hap value is translated to these Csound pfields: p1 -- Csou' },
        { label: 'defragmentHaps', detail: 'function', info: 'Combines adjacent haps with the same value and whole. Only intended for use in tests.' },
        { label: 'duck', detail: 'function', info: 'Modulate the amplitude of an orbit to create a "sidechain" like effect. Can be applied to multiple orbits with the ":" m' },
        { label: 'duckatt', detail: 'function', info: 'The time required for the ducked signal(s) to return to their normal volume. Can vary across orbits with the ":" mininot' },
        { label: 'duckattack', detail: 'function', info: 'The time required for the ducked signal(s) to return to their normal volume. Can vary across orbits with the ":" mininot' },
        { label: 'duckdepth', detail: 'function', info: 'The amount of ducking applied to target orbit Can vary across orbits with the ":" mininotation, e.g. duckdepth("0.3:0.1"' },
        { label: 'duckons', detail: 'function', info: 'The time required for the ducked signal(s) to reach their lowest volume. Can be used to prevent clicking or for creative' },
        { label: 'duckonset', detail: 'function', info: 'The time required for the ducked signal(s) to reach their lowest volume. Can be used to prevent clicking or for creative' },
        { label: 'duckorbit', detail: 'function', info: 'Modulate the amplitude of an orbit to create a "sidechain" like effect. Can be applied to multiple orbits with the ":" m' },
        { label: 'dur', detail: 'function', info: 'Sets the duration of the event in cycles. Similar to clip / legato, it also cuts samples off at the end if they exceed t' },
        { label: 'duration', detail: 'function', info: 'Sets the duration of the event in cycles. Similar to clip / legato, it also cuts samples off at the end if they exceed t' },
        { label: 'echo', detail: 'function', info: 'Superimpose and offset multiple times, gradually decreasing the velocity times : number - how many times to repeat time' },
        { label: 'findPeaks', detail: 'function', info: 'Find peaks in spectrum magnitudes' },
        { label: 'firstCycleValues', detail: 'function', info: 'Accessor for a list of values returned by querying the first cycle.' },
        { label: 'fit', detail: 'function', info: 'Makes the sample fit its event duration. Good for rhythmical loops like drum breaks. Similar to loopAt. samples({ rhodes' },
        { label: 'fmap', detail: 'function', info: 'see withValue' },
        { label: 'fmh', detail: 'function', info: 'Sets the Frequency Modulation Harmonicity Ratio. Controls the timbre of the sound. Whole numbers and simple ratios sound' },
        { label: 'fmi', detail: 'function', info: 'Sets the Frequency Modulation of the synth. Controls the modulation index, which defines the brightness of the sound. br' },
        { label: 'gap', detail: 'function', info: 'Does absolutely nothing, but with a given metrical "steps" steps : number gap(3) // "~@3"' },
        { label: 'generateGraph', detail: 'function', info: 'Creates a canvas element showing a graph of the given data. data : Float32Array - An array of numbers, or a Float32Array' },
        { label: 'gravX', detail: 'function', info: 'The device"s gravity x-axis value ranges from 0 to 1.' },
        { label: 'gravY', detail: 'function', info: 'The device"s gravity y-axis value ranges from 0 to 1.' },
        { label: 'gravZ', detail: 'function', info: 'The device"s gravity z-axis value ranges from 0 to 1.' },
        { label: 'gravityX', detail: 'function', info: 'The device"s gravity x-axis value ranges from 0 to 1.' },
        { label: 'gravityY', detail: 'function', info: 'The device"s gravity y-axis value ranges from 0 to 1.' },
        { label: 'gravityZ', detail: 'function', info: 'The device"s gravity z-axis value ranges from 0 to 1.' },
        { label: 'handleOutputBuffersToRetrieve', detail: 'function', info: 'Add contents of output buffers just processed to output buffers' },
        { label: 'inhabitmod', detail: 'function', info: 'The same as inhabit, but if you pick a number greater than the size of the list, it wraps around, rather than sticking a' },
        { label: 'inside', detail: 'function', info: 'Carries out an operation "inside" a cycle. "0 1 2 3 4 3 2 1".inside(4, rev).scale("C major").note() // "0 1 2 3 4 3 2 1"' },
        { label: 'keyDown', detail: 'function', info: 'returns true when a key or array of keys is held Key name reference keyDown("Control:j").pick([s("bd(5,8)"), s("cp(3,8)"' },
        { label: 'label', detail: 'function', info: 'Sets the displayed text for an event on the pianoroll label : string - text to display' },
        { label: 'legato', detail: 'function', info: 'Multiplies the duration with the given number. Also cuts samples off at the end if they exceed the duration. factor : nu' },
        { label: 'log', detail: 'function', info: 'Writes the content of the current event to the console (visible in the side menu).' },
        { label: 'logValues', detail: 'function', info: 'A simplified version of log which writes all "values" (various configurable parameters) within the event to the console' },
        { label: 'loop', detail: 'function', info: 'Loops the sample. Note that the tempo of the loop is not synced with the cycle tempo. To change the loop region, use loo' },
        { label: 'loopAt', detail: 'function', info: 'Makes the sample fit the given number of cycles by changing the speed. samples({ rhodes: "https://cdn.freesound.org/prev' },
        { label: 'loopAtCps', detail: 'function', info: 'Makes the sample fit the given number of cycles and cps value, by changing the speed. Please note that at some point cps' },
        { label: 'loopBegin', detail: 'function', info: 'Begin to loop at a specific point in the sample (inbetween begin and end). Note that the loop point must be inbetween be' },
        { label: 'loopEnd', detail: 'function', info: 'End the looping section at a specific point in the sample (inbetween begin and end). Note that the loop point must be in' },
        { label: 'loopb', detail: 'function', info: 'Begin to loop at a specific point in the sample (inbetween begin and end). Note that the loop point must be inbetween be' },
        { label: 'loope', detail: 'function', info: 'End the looping section at a specific point in the sample (inbetween begin and end). Note that the loop point must be in' },
        { label: 'lsize', detail: 'function', info: 'Physical size of the cabinet in meters. Be careful, it might be slightly larger than your computer. Affects the Doppler' },
        { label: 'markcss', detail: 'function', info: 'Overrides the css of highlighted events. Make sure to use single quotes! note("c a f e") .markcss("text-decoration:under' },
        { label: 'midi', detail: 'function', info: 'MIDI output: Opens a MIDI output port. midiport : string | number - MIDI device name or index defaulting to 0 options :' },
        { label: 'midin', detail: 'function', info: 'MIDI input: Opens a MIDI input port to receive MIDI control change messages. input : string | number - MIDI device name' },
        { label: 'morph', detail: 'function', info: 'Takes two binary rhythms represented as lists of 1s and 0s, and a number between 0 and 1 that morphs between them. The t' },
        { label: 'mousex', detail: 'function', info: 'The mouse"s x position value ranges from 0 to 1.' },
        { label: 'mousey', detail: 'function', info: 'The mouse"s y position value ranges from 0 to 1.' },
        { label: 'nrpnn', detail: 'function', info: 'MIDI NRPN non-registered parameter number: Sends a MIDI NRPN non-registered parameter number message. nrpnn : number | P' },
        { label: 'nrpv', detail: 'function', info: 'MIDI NRPN non-registered parameter value: Sends a MIDI NRPN non-registered parameter value message. nrpv : number | Patt' },
        { label: 'onTriggerTime', detail: 'function', info: 'make something happen on event time uses browser timeout which is innacurate for audio tasks' },
        { label: 'oriA', detail: 'function', info: 'The device"s orientation alpha value ranges from 0 to 1.' },
        { label: 'oriB', detail: 'function', info: 'The device"s orientation beta value ranges from 0 to 1.' },
        { label: 'oriG', detail: 'function', info: 'The device"s orientation gamma value ranges from 0 to 1.' },
        { label: 'oriX', detail: 'function', info: 'The device"s orientation beta value ranges from 0 to 1.' },
        { label: 'oriY', detail: 'function', info: 'The device"s orientation gamma value ranges from 0 to 1.' },
        { label: 'oriZ', detail: 'function', info: 'The device"s orientation alpha value ranges from 0 to 1.' },
        { label: 'orientationAlpha', detail: 'function', info: 'The device"s orientation alpha value ranges from 0 to 1.' },
        { label: 'orientationBeta', detail: 'function', info: 'The device"s orientation beta value ranges from 0 to 1.' },
        { label: 'orientationGamma', detail: 'function', info: 'The device"s orientation gamma value ranges from 0 to 1.' },
        { label: 'orientationX', detail: 'function', info: 'The device"s orientation beta value ranges from 0 to 1.' },
        { label: 'orientationY', detail: 'function', info: 'The device"s orientation gamma value ranges from 0 to 1.' },
        { label: 'orientationZ', detail: 'function', info: 'The device"s orientation alpha value ranges from 0 to 1.' },
        { label: 'outside', detail: 'function', info: 'Carries out an operation "outside" a cycle. "<[0 1] 2 [3 4] 5>".outside(4, rev).scale("C major").note() // "<[0 1] 2 [3' },
        { label: 'pickmod', detail: 'function', info: 'The same as pick, but if you pick a number greater than the size of the list, it wraps around, rather than sticking at t' },
        { label: 'pickmodF', detail: 'function', info: 'The same as pickF, but if you pick a number greater than the size of the functions list, it wraps around, rather than st' },
        { label: 'pickmodOut', detail: 'function', info: 'The same as pickOut, but if you pick a number greater than the size of the list, it wraps around, rather than sticking a' },
        { label: 'pickmodReset', detail: 'function', info: 'The same as pickReset, but if you pick a number greater than the size of the list, it wraps around, rather than sticking' },
        { label: 'pickmodRestart', detail: 'function', info: 'The same as pickRestart, but if you pick a number greater than the size of the list, it wraps around, rather than sticki' },
        { label: 'pickmodSqueeze', detail: 'function', info: 'The same as inhabit, but if you pick a number greater than the size of the list, it wraps around, rather than sticking a' },
        { label: 'pitchwheel', detail: 'function', info: 'Renders a pitch circle to visualize frequencies within one octave hapcircles : number circle : number edo : number root' },
        { label: 'prepareInputBuffersToSend', detail: 'function', info: 'Copy contents of input buffers to buffer actually sent to process' },
        { label: 'pure', detail: 'function', info: 'A discrete value that repeats once per cycle. pure("e4") // "e4"' }
    ]
};

// Export for use
if (typeof module !== 'undefined') {
    module.exports = StrudelAutocomplete;
}
if (typeof window !== 'undefined') {
    window.StrudelAutocomplete = StrudelAutocomplete;
}